#!/usr/bin/env python3
"""
Test the cookiecutter
"""
import argparse
import os
import shlex
import sys

from tempfile import TemporaryDirectory
from subprocess import run, CalledProcessError

CUTTER_DIR = os.path.abspath(os.path.dirname(__file__))

CMAKE_CMD = ["cmake", "-G", "Ninja"]
NINJA_CMD = ["ninja"]

TARGET_DICT = {
    "lupdate": ["lupdate"],
    "build": [],
    "test": ["test"]
}


def check_run(cmd, **kwargs):
    kwargs = dict(kwargs)
    kwargs["check"] = True
    cmd_str = " ".join(shlex.quote(x) for x in cmd)
    print(f"# Running '{cmd_str}'")
    try:
        return run(cmd, **kwargs)
    except CalledProcessError:
        print(f"# Command '{cmd_str}' failed")
        sys.exit(1)


def main():
    target_names = ", ".join(x for x in TARGET_DICT.keys())

    parser = argparse.ArgumentParser()
    parser.description = __doc__

    parser.add_argument("-s", "--shell", action="store_true",
                        help="Run a shell at the end")

    parser.add_argument("-D", dest="cmake", action="append",
                        help="Additional cmake cache entry")

    parser.add_argument("-v", "--verbose", action="store_true",
                        help="Pass -v argument to ninja")

    parser.add_argument("targets", nargs="*",
                        help="Targets to run. Must be a subset of:"
                        f" {target_names}. Defaults to all targets.")

    args = parser.parse_args()
    if args.targets:
        targets = []
        for name in args.targets:
            try:
                target = TARGET_DICT[name]
            except KeyError:
                print(f"Invalid target {name}")
                return 1
            targets.append(target)
    else:
        targets = TARGET_DICT.values()

    if args.verbose:
        NINJA_CMD.append("-v")

    if args.cmake:
        CMAKE_CMD.extend([f"-D{x}" for x in args.cmake])

    with TemporaryDirectory(prefix="cookiecutter-qt-app-") as temp_dir:
        os.chdir(temp_dir)
        check_run(["cookiecutter", CUTTER_DIR, "--no-input"])
        os.chdir("qt-app")
        check_run(CMAKE_CMD + ["-B", "build"])
        os.chdir("build")
        for target in targets:
            check_run(NINJA_CMD + target)
        if args.shell:
            check_run([os.environ["SHELL"]])

    return 0


if __name__ == "__main__":
    sys.exit(main())
# vi: ts=4 sw=4 et
