#!/usr/bin/env python3
"""
Test the cookiecutter
"""
import argparse
import os
import shlex
import sys

from tempfile import TemporaryDirectory
from subprocess import run

CUTTER_DIR = os.path.abspath(os.path.dirname(__file__))

CMAKE_CMD = ["cmake", "-G", "Ninja"]
NINJA_CMD = ["ninja"]


def check_run(cmd, **kwargs):
    kwargs = dict(kwargs)
    kwargs["check"] = True
    cmd_str = " ".join(shlex.quote(x) for x in cmd)
    print(f"# Running {cmd_str}")
    return run(cmd, **kwargs)


def main():
    parser = argparse.ArgumentParser()
    parser.description = __doc__

    parser.add_argument("-s", "--shell", action="store_true",
                        help="Run a shell at the end")

    parser.add_argument("-D", dest="cmake", action="append",
                        help="Additional cmake cache entry")

    parser.add_argument("-v", "--verbose", action="store_true",
                        help="Pass -v argument to ninja")

    args = parser.parse_args()

    if args.verbose:
        NINJA_CMD.append("-v")

    if args.cmake:
        CMAKE_CMD.extend([f"-D{x}" for x in args.cmake])

    with TemporaryDirectory(prefix="cookiecutter-qt-app-") as temp_dir:
        os.chdir(temp_dir)
        check_run(["cookiecutter", CUTTER_DIR, "--no-input"])
        os.chdir("qt-app")
        check_run(CMAKE_CMD + ["-B", "build"])
        os.chdir("build")
        check_run(NINJA_CMD)
        check_run(NINJA_CMD + ["test"])
        if args.shell:
            check_run([os.environ["SHELL"]])

    return 0


if __name__ == "__main__":
    sys.exit(main())
# vi: ts=4 sw=4 et
