#!/bin/bash
set -euo pipefail

COOKIECUTTER_VERSION=1.7.2

pushd $PWD > /dev/null
cd $(dirname $0)/..
SRC_DIR=$PWD
popd > /dev/null

WORK_DIR=${WORK_DIR:-$SRC_DIR/_work}

. $SRC_DIR/{{cookiecutter.project_slug}}/ci/lib/common.sh

main() {
    echo_title "Installing cookiecutter"
    init_python_cmd
    $PYTHON_CMD -m pip install --upgrade pip setuptools
    $PYTHON_CMD -m pip install cookiecutter==$COOKIECUTTER_VERSION

    echo_title "Cutting the cookie"
    rm -rf "$WORK_DIR"
    mkdir "$WORK_DIR"
    cd "$WORK_DIR"
    $PYTHON_CMD -m cookiecutter "$SRC_DIR" --no-input
}

main
