#!/bin/bash
set -exuo pipefail

pushd $PWD > /dev/null
cd $(dirname $0)
CI_DIR=$PWD
popd > /dev/null

INST_DIR="$1"
ENV_FILE="$2"

QT_ARCH_WINDOWS=win64_msvc2017_64
QT_ARCH_MACOS=clang_64
QT_VERSION=5.12.8

ECM_VERSION=5.69.0

detect_os() {
    local out
    out=$(uname)

    case "$out" in
    Linux)
        OS="linux"
        ;;
    Darwin)
        OS="macos"
        ;;
    MINGW*)
        OS="windows"
        ;;
    *)
        echo "Unknown OS. uname printed '$out'"
        exit 1
        ;;
    esac
}

add_env_var() {
    echo "export $1=$2" >> $ENV_FILE
    export $1=$2
}

prepend_path() {
    echo "export PATH=$1:\$PATH" >> $ENV_FILE
    export PATH=$1:$PATH
}

setup_python() {
    case $OS in
    windows)
        add_env_var PYTHON_CMD python
        ;;
    *)
        add_env_var PYTHON_CMD python3
        ;;
    esac
    $PYTHON_CMD -m pip install --upgrade pip
    $PYTHON_CMD -m pip install setuptools
}

install_qt() {
    local os=$1
    local arch=$2
    local qt_install_dir=$INST_DIR/qt
    $PYTHON_CMD -m pip install aqtinstall
    $PYTHON_CMD -m aqt install --outputdir $qt_install_dir $QT_VERSION $os desktop $arch
    if [ "$OS" = "windows" ] ; then
        # Add Qt bin dir to $PATH so that tests can find Qt dlls
        prepend_path $(find $qt_install_dir -type d -a -name bin)
    fi
    # Add Qt plugins dir to $QT_PLUGIN_PATH because the official Qt installer
    # patches QtCore dll so that it finds its plugins, but aqt does not.
    # Not being able to find plugins causes tests to not run on macOS and
    # Windows because they can't find the matching platform plugin.
    add_env_var QT_PLUGIN_PATH $(find $qt_install_dir -type d -a -name plugins)
    add_env_var Qt5_DIR $(find $qt_install_dir -path '*/lib/cmake')
}

install_linux_packages() {
    sudo apt-get install -y --no-install-recommends \
        cmake \
        extra-cmake-modules \
        qtbase5-dev \
        qttools5-dev \
        xvfb
}

install_catch2() {
    git clone --depth 1 https://github.com/catchorg/Catch2.git
    (
        cd Catch2
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=$INST_DIR -DBUILD_TESTING=OFF ..
        cmake --build .
        cmake --build . --target install
    )
}

install_ecm() {
    git clone --depth 1 https://anongit.kde.org/extra-cmake-modules.git -b v$ECM_VERSION
    (
        cd extra-cmake-modules
        mkdir build
        cd build
        cmake \
            -DCMAKE_INSTALL_PREFIX=$INST_DIR \
            -DBUILD_HTML_DOCS=OFF \
            -DBUILD_MAN_DOCS=OFF \
            -DBUILD_QTHELP_DOCS=OFF \
            -DBUILD_TESTING=OFF \
            ..
        cmake --build .
        cmake --build . --target install
    )
}

install_macos_packages() {
    install_qt mac $QT_ARCH_MACOS
    install_ecm
}

install_windows_packages() {
    install_qt windows $QT_ARCH_WINDOWS
    install_ecm
}

install_runtest_deps() {
    $PYTHON_CMD -m pip install -r $CI_DIR/../requirements.txt
}

rm -f $ENV_FILE
touch $ENV_FILE
detect_os
if [ "$OS" = "windows" ] ; then
    INST_DIR=$(cygpath $INST_DIR)
    ENV_FILE=$(cygpath $ENV_FILE)
fi

setup_python

case "$OS" in
linux)
    install_linux_packages
    ;;
macos)
    install_macos_packages
    ;;
windows)
    install_windows_packages
    ;;
esac

install_catch2
install_runtest_deps
