name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      PYTHONUNBUFFERED: 1
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            triplet: x64-linux
          - os: windows-latest
            triplet: x64-windows
          - os: macos-latest
            triplet: x64-osx

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ci/build
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: _work/qt-app/build/qt-app[-_]*.*
