name: main

on:
  push:
    branches:
      - master
      - dev
      - wip/ci
    tags: "[0-9]*"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      PYTHONUNBUFFERED: 1
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        include:
          - os: ubuntu-latest
            triplet: x64-linux
          # - os: windows-latest
          #   triplet: x64-windows
          # - os: macos-latest
          #   triplet: x64-osx

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: ci/install-dependencies
      - name: Run test script
        run: python3 runtests.py -DCMAKE_PREFIX_PATH=$HOME/inst
